theme = "nord_dark2"

[editor]
scrolloff = 10
line-number = "absolute"
bufferline = "always"
scroll-lines = 3
mouse = true
color-modes = true
# Resolve true color detection problems (e.g. on Linux in Windows WSL2)
# such as the error, "theme: theme requires true color support".
true-color = true
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name" ]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"
ret = ["move_line_down", "goto_first_nonwhitespace"]
0   = "goto_first_nonwhitespace"
"C-d" = ["half_page_down", "goto_window_center"]
"C-u" = ["half_page_up", "goto_window_center"]
"D" = ["ensure_selections_forward", "extend_to_line_end"]
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.normal.space]
"i" = ":toggle lsp.display-inlay-hints"
"c" = ":set gutters.line-numbers.min-width 30"
"C" = ":set gutters.line-numbers.min-width 1"


[keys.select]
X = ["extend_line_up", "extend_to_line_bounds"]
A-x = "extend_to_line_bounds"
