theme = "mutable2"

[editor]
scrolloff = 10
bufferline = "multiple"
scroll-lines = 3
mouse = true
color-modes = true
# Resolve true color detection problems (e.g. on Linux in Windows WSL2)
# such as the error, "theme: theme requires true color support"
true-color = true
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name" ]
right = ["diagnostics", "workspace-diagnostics" , "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
# handles multi-cursors and multi line visual selections with a single key
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["move_line_down", "goto_first_nonwhitespace"]
"X" = ["extend_line_up", "extend_to_line_bounds"]
"D" = ["ensure_selections_forward", "extend_to_line_end"]
"0"   = "goto_first_nonwhitespace"
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

"C-d" = ["half_page_down", "goto_window_center"]
"C-u" = ["half_page_up", "goto_window_center"]
"C-x" = "extend_to_line_bounds"

"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"
"A-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"A-down"= ["extend_to_line_bounds", "delete_selection", "paste_after"]

"F1" = ":config-open"
"F2" = ":config-reload"
"F3" = ":buffer-close!"

[keys.normal.space]
"i" = ":toggle lsp.display-inlay-hints"
"\\" = ":reload-all"
"=" = ":format"
x = ":buffer-close!"


# Add comma to the end of the line,
"," = [
    "save_selection",
    "goto_line_end",
    ":append-output echo ,",
    "collapse_selection",
    "delete_selection",
    "jump_backward",
]
# Add semicolumn to the end of the line
";" = [
    "save_selection",
    "goto_line_end",
    ":append-output echo ;",
    "collapse_selection",
    "delete_selection",
    "jump_backward",
]
