# Author: RayGervais <raygervais@hotmail.ca>

"attribute" = "base09"
"comment" = { fg = "base03", modifiers = ["italic"] }
"constant.character.escape" = "base0C"
"constant.numeric" = "base09"
"constant" = "base09"
"constructor" = "yellow"
"function" = "base0D"
"keyword" = "base0E"

# 'keyword' = "#B8A1E2" # Language reserved keywords.
'keyword.control' = "base0E" # Control keywords.
'keyword.control.conditional' = "base0E" # `if`, `else`, `elif`.
'keyword.control.repeat' = "base0E" # `for`, `while`, `loop`.
'keyword.control.import' = "base0E" # `import`, `export` `use`.
'keyword.control.return' = "base0E" # `return` in most languages.
'keyword.control.exception' = "base0E" # `try`, `catch`, `raise`/`throw` and related.
'keyword.operator' = "base0E" # `or`, `and`, `in`.
'keyword.directive' = "white" # Preprocessor directives (#if in C...).
'keyword.function' = "base0E" # The keyword to define a function: 'def', 'fun', 'fn'.

"label" = "base0E"
"namespace" = "base0E"
"operator" = "base05"
"special" = "base0D"
"string"  = "#acca77"
"type" = "base0A"
"ui.background" = { bg = "base00" }
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.help" = { fg = "base06", bg = "base01" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.linenr" = { fg = "base03", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.popup" = { bg = "base01" }
"ui.selection" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.text.focus" = "base05"
"ui.text" = "base05"
"ui.virtual.inlay-hint" = { fg = "#9CA4AD" } 
"ui.virtual.jump-label" = { fg = "blue", modifiers = ["bold", "underlined"] }
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.whitespace" = "base03"
"ui.window" = { bg = "base01" }
"variable.other.member" = "base0B"
"variable" = "base05"

"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.heading" = "base0D"
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.link.text" = "base08"
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.list" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"diff.plus" = "base0B"
"diff.delta" = "base09"
"diff.minus" = "base08"

"diagnostic" = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "base01" }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base09"
"error" = "base08"

"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base06", bg = "base01" }

[palette]
base00 = "#181818" # Default Background
base01 = "#282828" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#383838" # Selection Background
base03 = "#808080" # Comments, Invisibles, Line Highlighting
base04 = "#b8b8b8" # Dark Foreground (Used for status bars)
base05 = "#d8d8d8" # Default Foreground, Caret, Delimiters, Operators
base06 = "#e8e8e8" # Light Foreground (Not often used)
base07 = "#f8f8f8" # Light Background (Not often used)
base08 = "#ab4642" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#dc9656" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#baa9da" # Classes, Markup Bold, Search Text Background
base0B = "#a1b56c" # Strings, Inherited Class, Markup Code, Diff Inserted
baseB1 = "#84BA97" # Constructor
base0C = "#86c1b9" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#7cafc2" # Functions, Methods, Attribute IDs, Headings
based1 = "#8FC4EB"
base0E = "#ba8baf" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#a16946" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
func   = "#8FBCBB"
cyan   = "#5dbbc1"